name: Continuous Deployment
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authorize in Docker
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build --platform linux/amd64 -t almaxgood/restaurant-app-frontend .

      - name: Push Docker image
        run: docker push almaxgood/restaurant-app-frontend

      - name: Install sshpass
        run: sudo apt install sshpass

      - name: Run on VM
        run: sshpass -p ${{ secrets.VM_PASSWORD }} ssh -o StrictHostKeyChecking=no root@${{ secrets.VM_IP }}
          'cd ~/restaurant-app-frontend &&
          docker compose down &&
          docker system prune -a -f --volumes &&
          docker compose up -d'