name: Continuous Integration
on:
  pull_request:
    branches: [ main, dev ]
  push:
    branches: [ dev ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authorize in Docker
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build --platform linux/amd64 -t almaxgood/restaurant-app-frontend:temp .

      - name: Push Docker image
        run: docker push almaxgood/restaurant-app-frontend:temp

      - name: Run Docker container
        run: docker run -t --name restaurant-app-frontend -d -p 3000:3000 almaxgood/restaurant-app-frontend:temp

      - name: Wait Docker container to start
        uses: GuillaumeFalourd/wait-sleep-action@v1
        with:
          time: '15'

      - name: Show Docker container logs
        run: docker logs restaurant-app-frontend