name: Continuous Integration
on:
  push:
    branches: [ dev ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Docker container
        run: docker build --platform linux/amd64 -t almaxgood/restaurant-app-frontend .
      - name: Authorize in Docker
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Docker container
        run: docker push almaxgood/restaurant-app-frontend
      - name: Connect to VM
        run: |
          ssh root@31.129.98.43
          ${{ secrets.VM_PASSWORD }}
      - name: Run docker container
        run: |
          cd ~/restaurant-app-frontend
          docker compose down
          docker system prune -a -f
          docker compose up -d